services:
  personal-site:
    build: .
    image: personal-site:latest
    networks:
      - traefik-network
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.personal-site.rule=(Host(`jslabs.es`) || Host(`jslabs.eu`) || Host(`jslabs.ddns.net`))"
      - "traefik.http.routers.personal-site.entrypoints=websecure"
      - "traefik.http.routers.personal-site.tls=true"
      - "traefik.http.routers.personal-site.tls.certresolver=letsencrypt"
      - "traefik.http.services.personal-site.loadbalancer.server.port=8000"
    read_only: true
    tmpfs:
      - /tmp
      - /var/run
    security_opt:
      - no-new-privileges:true
    cap_drop:
      - ALL
    cap_add: []
    stop_grace_period: 20s
    deploy:
      replicas: 1
      restart_policy:
        condition: unless-stopped
      update_config:
        parallelism: 1
        delay: 10s
        failure_action: rollback
      rollback_config:
        parallelism: 1
        delay: 0s

networks:
  traefik-network:
    external: true

